### ISSUE TITLE
Fix Circle CI build

### ISSUE THREAD

**Issue by BeppeTW** [thoughtworks/templify#4]
**Tasks** 
- [x] Configurar build maven no circleci.
- [x] Adicionar badge com status do pipeline no readme.
- [x] Publicar os resultados do surefire no build.
